# Generated by Django 4.0.5 on 2022-06-26 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d54e3f7a-6ab5-401b-a891-62afceb148cb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
