# Generated by Django 4.0.5 on 2022-07-11 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_created_at_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0c746d67-5d72-4096-a906-e5839f99158d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
