# Generated by Django 4.0.5 on 2022-07-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RDSOPro.roles')),
            ],
        ),
        migrations.CreateModel(
            name='DrawerFields',
            fields=[
                ('field_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=100)),
                ('field_link', models.URLField()),
                ('role_id', models.ManyToManyField(blank=True, to='RDSOPro.roles')),
            ],
        ),
    ]
