# Generated by Django 4.0.6 on 2022-07-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0002_amcfirmmaster_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role_id',
        ),
        migrations.AddField(
            model_name='users',
            name='role_id',
            field=models.ManyToManyField(blank=True, related_name='user', to='RDSOPro.roles'),
        ),
    ]
