# Generated by Django 4.0.5 on 2022-07-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0002_amcfirmmaster_comappcommappprofileretire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comappcommappprofileretire',
            options={'managed': True},
        ),
    ]
