# Generated by Django 4.0.6 on 2022-07-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0003_remove_users_role_id_users_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdsoproUsersRoleId',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'RDSOPro_users_role_id',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='drawerfields',
            name='role_id',
        ),
        migrations.AddField(
            model_name='roles',
            name='field_id',
            field=models.ManyToManyField(blank=True, related_name='role', to='RDSOPro.drawerfields'),
        ),
    ]
