# Generated by Django 4.0.5 on 2022-07-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0003_alter_comappcommappprofileretire_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comappcommappprofileretire',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commapplogin',
            options={},
        ),
    ]
