# Generated by Django 4.0.5 on 2022-07-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0004_alter_comappcommappprofileretire_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comappcommappprofileretire',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='commapplogin',
            options={'managed': False},
        ),
    ]
