# Generated by Django 4.0.6 on 2022-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0004_rdsoprousersroleid_remove_drawerfields_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdsoproRolesFieldId',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('roles_id', models.IntegerField()),
                ('drawerfields_id', models.IntegerField()),
            ],
            options={
                'db_table': 'RDSOPro_roles_field_id',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='RdsoproDrawerfieldsRoleId',
        ),
    ]
