# Generated by Django 4.0.6 on 2022-07-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0005_rdsoprorolesfieldid_delete_rdsoprodrawerfieldsroleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawerfields',
            name='field_link',
            field=models.CharField(max_length=200),
        ),
    ]
