# Generated by Django 4.0.6 on 2022-07-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0006_alter_drawerfields_field_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawerfields',
            options={'ordering': ['field_id']},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['role_id']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['user_id']},
        ),
    ]
