# Generated by Django 4.0.5 on 2022-07-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0006_alter_amcfirmmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commdtemaster',
            name='vertical_dte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RDSOPro.commverticaldtemaster'),
        ),
        migrations.AddField(
            model_name='complaintregistration',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RDSOPro.complaintforemanteam'),
        ),
        migrations.AlterUniqueTogether(
            name='commapploginmaster',
            unique_together={('ipasid', 'aadhar_no')},
        ),
        migrations.AlterUniqueTogether(
            name='commapploginmaster1',
            unique_together={('ipasid', 'aadhar_no')},
        ),
        migrations.AlterUniqueTogether(
            name='commempfamily',
            unique_together={('ipas', 'member_index')},
        ),
        migrations.AlterUniqueTogether(
            name='commnonrdsoapppriv',
            unique_together={('aadhar_no', 'appid')},
        ),
        migrations.AlterUniqueTogether(
            name='commrolepriv',
            unique_together={('role_id', 'menu_id')},
        ),
        migrations.AlterUniqueTogether(
            name='commverifyrole',
            unique_together={('ipasid', 'dte_id', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='complaintareacategory',
            unique_together={('directorate_id', 'complaint_category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='complaintforemanteam',
            unique_together={('directorate_id', 'member_id')},
        ),
        migrations.AlterUniqueTogether(
            name='complaintmenumaster',
            unique_together={('menu_id', 'menu_name')},
        ),
        migrations.AlterUniqueTogether(
            name='paybandmaster',
            unique_together={('pay_band_scale', 'grade_pay')},
        ),
    ]
