# Generated by Django 4.0.6 on 2022-08-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0007_alter_drawerfields_options_alter_roles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTrains',
            fields=[
                ('train_no', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['train_no'],
            },
        ),
        
    ]
