# Generated by Django 4.0.6 on 2022-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDSOPro', '0008_newtrains_drawerfields_field_icon'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='newtrains',
            name='d_date_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtrains',
            name='fare',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newtrains',
            name='s_date_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
