# Generated by Django 4.0.5 on 2022-07-15 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f6c0bb20-9ab1-4a34-9774-6ba719be3a2a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
