# Generated by Django 4.0.5 on 2022-07-15 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a572373e-051b-45dd-8f19-9d6d47338236'), editable=False, primary_key=True, serialize=False),
        ),
    ]
