# Generated by Django 4.0.5 on 2022-07-13 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('247e5741-0324-44ce-b7c9-0e7bd9084b6f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
