# Generated by Django 4.0.5 on 2022-07-15 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('af9902a7-48ac-486e-a088-50ba0080f46c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
