# Generated by Django 4.0.5 on 2022-07-15 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9c690a74-e07e-44a5-9c07-05971ff0ebbe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
