# Generated by Django 4.0.5 on 2022-07-15 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('791c899c-7a67-426a-ae3d-b1b8fae4a341'), editable=False, primary_key=True, serialize=False),
        ),
    ]
