# Generated by Django 4.0.5 on 2022-07-15 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4f104342-e3a5-49c0-ac6c-bbf74209e26f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
