# Generated by Django 4.0.5 on 2022-07-15 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ac48fb10-cf7b-48a8-aac2-8f910911ff7f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
