# Generated by Django 4.0.5 on 2022-07-15 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('83b0f3fc-38ed-4dc6-9ccc-442f7779d323'), editable=False, primary_key=True, serialize=False),
        ),
    ]
