# Generated by Django 4.0.5 on 2022-07-15 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e25d69e0-354d-4971-8843-ae5939b1f670'), editable=False, primary_key=True, serialize=False),
        ),
    ]
