# Generated by Django 4.0.5 on 2022-07-15 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0cf22694-6d04-4ec8-abf3-08582a17186e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
