# Generated by Django 4.0.5 on 2022-07-15 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('950e1ee4-50e9-47b9-af5e-ef132f1cb6d9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
