# Generated by Django 4.0.5 on 2022-07-15 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('605ffb3d-b2b7-489e-bdd7-42f60670c44a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
