# Generated by Django 4.0.5 on 2022-07-15 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('047da958-f444-4df2-a8f0-db7a35e1f496'), editable=False, primary_key=True, serialize=False),
        ),
    ]
