# Generated by Django 4.0.5 on 2022-07-15 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bf7c9152-4ec4-468a-92e6-d986fa63c1ec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
