# Generated by Django 4.0.5 on 2022-07-15 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5f1d8384-d6d6-465e-a336-161f7e68b763'), editable=False, primary_key=True, serialize=False),
        ),
    ]
