# Generated by Django 4.0.5 on 2022-07-15 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c6ce3833-4336-43f9-819b-bb2dec3a5e9d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
