# Generated by Django 4.0.5 on 2022-07-16 04:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0a380581-f3cc-4949-9274-33ed106183d1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
