# Generated by Django 4.0.5 on 2022-07-16 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('08e929aa-d2e5-42f5-916a-750819a2cfce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
