# Generated by Django 4.0.5 on 2022-07-16 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d3d0edb1-28a2-4f23-a5b3-92087d407089'), editable=False, primary_key=True, serialize=False),
        ),
    ]
