# Generated by Django 4.0.5 on 2022-07-16 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('77eb115a-8a89-41c1-93e9-e08a49871633'), editable=False, primary_key=True, serialize=False),
        ),
    ]
