# Generated by Django 4.0.5 on 2022-07-16 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('eacaa83b-3118-4203-bd1f-86a07f1cf278'), editable=False, primary_key=True, serialize=False),
        ),
    ]
