# Generated by Django 4.0.5 on 2022-07-16 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0b7c3248-46d4-449d-8f1f-6e07ddbfbdf4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
