# Generated by Django 4.0.5 on 2022-07-16 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0eb99b08-49c9-48c1-bb20-fe822bc390bc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
