# Generated by Django 4.0.6 on 2022-07-16 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1d456db5-e262-42d1-b025-ae5c46a3672a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
