# Generated by Django 4.0.6 on 2022-07-17 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4baa7edc-951a-442d-ad44-1abfd866cce6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
