# Generated by Django 4.0.6 on 2022-07-17 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1f25722d-d1b9-4940-8203-7302a8f806c5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
