# Generated by Django 4.0.6 on 2022-07-17 04:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('59a69300-dc79-41a1-b830-81c9e89eba53'), editable=False, primary_key=True, serialize=False),
        ),
    ]
