# Generated by Django 4.0.6 on 2022-07-17 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('98156b96-25d9-4609-befd-03ff6bdbfb50'), editable=False, primary_key=True, serialize=False),
        ),
    ]
