# Generated by Django 4.0.6 on 2022-07-17 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('af757806-31ba-4d7c-8d38-9e8dfb987c43'), editable=False, primary_key=True, serialize=False),
        ),
    ]
