# Generated by Django 4.0.6 on 2022-07-19 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('36a3b0a2-b837-42ab-9629-23b9634b1389'), editable=False, primary_key=True, serialize=False),
        ),
    ]
