# Generated by Django 4.0.6 on 2022-07-20 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0056610a-f4ca-45b9-9fd1-b38cbb869a99'), editable=False, primary_key=True, serialize=False),
        ),
    ]
