# Generated by Django 4.0.6 on 2022-07-24 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d98ec3ef-98e0-4cc0-9d10-286c0a0bae95'), editable=False, primary_key=True, serialize=False),
        ),
    ]
