# Generated by Django 4.0.6 on 2022-07-24 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a8d185ca-a0fd-4178-899c-e2d085060a34'), editable=False, primary_key=True, serialize=False),
        ),
    ]
