# Generated by Django 4.0.6 on 2022-07-24 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('66ec991f-9811-4f2f-b5a5-8e666514a3ce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
