# Generated by Django 4.0.6 on 2022-08-21 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bf5c1e21-9c84-4922-aad8-e8cec0a1100d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
