# Generated by Django 4.0.6 on 2022-08-21 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a65accc5-0dea-489f-97bd-c6901fdeed6f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
